### ISSUE TITLE
Trackpad not working

### ISSUE THREAD

**Issue by danielrumata** [danielrumata/Legion-5800H-Hackintosh#1]
As you can see in this guide, I couldn't manage to get the touchpad working. If you have any ideas how to enable touchpad feel free to post it here.

**Comment by MinecraftNerrd1337** [comment]
Remove SSDT-HPET and its patches

**Comment by danielrumata** [comment]
> Remove SSDT-HPET and its patches
> 
> That fixed the Synaptics trackpad for my Legion. I'd be able to help further if you gave me your trackpad ID (not PNP0C50, the actual ID)

It worked for me too! You are a hero! Thank you very much!
